name: Java CI

on:
  push:
  pull_request:
  schedule: [ cron: '29 2 * * 5' ] # weekly: At 02:29 on Friday

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 17 ]
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'

      - name: Build
        run: mvn --batch-mode --show-version --no-transfer-progress -D CI=GitHub install
